### ISSUE TITLE
Not working optimized Pillar parser

### ISSUE THREAD

**Issue by JurajKubelka** [kursjan/petitparser2#20]
Hi @kursjan,

we have migrated Pillar parser to use Petit parser 2. We have spotted one issue using `optimize` and `PP2GuardVisitor` is the responsible one.

Here is the example:
```Smalltalk
PR2PillarParser new parse: 'a'. "--> returns a PRDocument object"
PR2PillarParser new optimize parse: 'a'. "--> produces an error and it should not"
```

### Steps to reproduce:

Currently, the Pillar parser is stored in [Documenter](https://github.com/feenkcom/gtoolkit-documenter) repository. You can install it in Pharo 6.1 using: 

```Smalltalk
Metacello new
   baseline: 'GToolkitDocumenter';
   repository: 'github://feenkcom/gtoolkit-documenter/src';
   load.
```

I will appreciate if you can help us with it. I do not understand how to debug `PP2GuardVisitor` optimizations.

**Comment by girba** [comment]
Indeed, it would be great to get support for this issue. I would also be very interested to learn how to debug such issues in the future, too :)

**Comment by kursjan** [comment]
Thanks for migrating to PP2!

I commited a fix [1], I will add some details about why/how to debug during the weekend.

[1]: https://github.com/kursjan/petitparser2/commit/36f878bdd658de5a6cfaef18f25ebfaf977bb2b9

**Comment by JurajKubelka** [comment]
Thank you! I can confirm that 36f878bdd658de5a6cfaef18f25ebfaf977bb2b9 fixes the issue.

**Comment by girba** [comment]
Thanks a lot, @kursjan! After migrating to PP2, we got a parsing speedup of 2x, which is very relevant for tooling.

```
pp1 := GtPillarExtendedParser new.
[
    100 timesRepeat: [
        pp1 parse:
    (IceRepository repositoriesLocation / 'feenkcom'/ 'gtoolkit-examples' / 'doc' / 'tutorial' / 'examples-tutorial.pillar') contents ] ] timeToRun
"0:00:00:05.545".


pp2 := PR2PillarParser new optimize.
[
    100 timesRepeat: [
        pp2 parse:
        (IceRepository repositoriesLocation / 'feenkcom'/ 'gtoolkit-examples' / 'doc' / 'tutorial' / 'examples-tutorial.pillar') contents ] ] timeToRun.  
 "0:00:00:02.347"
```

**Comment by kursjan** [comment]
Thanks @girba for the speedup report. 2x speedup is reasonable, I will have a look where are the inefficiencies if we can implement optimizations to improve it even more.

**Comment by kursjan** [comment]
### Now how to debug/fix this issue

I installed GUI component of PP2 (IMO Moose should do this by default).

I run your use-cases in the debug mode.
```Smalltalk
PR2PillarGrammar new debug: 'a'.
PR2PillarGrammar new optimize debug: 'a'. 
```
![screenshot from 2018-06-22 22-25-40](https://user-images.githubusercontent.com/4191369/41808802-70ae25d6-76e3-11e8-9d87-6ae9ce7aafe6.png)

In optimized mode, paragraph is properly parsed, but `lineEnd` parser fails because of a guard.
![screenshot from 2018-06-22 22-25-26](https://user-images.githubusercontent.com/4191369/41808825-b5b1b684-76e3-11e8-9baf-fa831b20cb35.png)

Inspecting the guard shows that guard does not fail if an input continues with `Character cr` or `Character lf` (comming from `newline`). The problem seems end of input (`#eoi asPParser`) in `lineEnd`. 
![screenshot from 2018-06-23 12-52-35](https://user-images.githubusercontent.com/4191369/41808863-6e7687e4-76e4-11e8-82d6-4fbcc54a73ac.png)

The main supect is `firstCharSet` method of `PP2EndOfInputNode`. It is rather unintuitive, because `#endOfInput` is a virtual character, is not a character in the input stream. Thus the return value should be unknown character set instead of empty character set (naming is confusing here :-1:)
![screenshot from 2018-06-23 12-55-21](https://user-images.githubusercontent.com/4191369/41808884-f0d7ce64-76e4-11e8-95d6-b08e81058a93.png)

PP2 deals with the rest on its own.

I was for a while confused with guards as well. It is usefull to check `PP2GuardVisitor`.
- It adds guards to all the children of choices (`visitChoice`), but not to the choice itself
- It adds guards to delegates (`visitDelegate`), this is the guard that made trouble in this bug, optional and repeating nodes (`visitOptional`, `visitPossesiveRepeating`)
- sequences (`visitSequence`) are visited guarding only the first node (not sure why :open_mouth:), trimmed nodes (`visitTrimming`) seem complicated (I don't remember what does it do :cry:)
